import Foundation

/// Brand catalog sourced from brand_list_568336_03-09-2026.csv
/// Merged at runtime with any brands found dynamically on ProductSKU records.
enum BrandCatalog {
    static let all: [String] = [
        "#hashtag",
        "3 Bros Grow",
        "818 Brands",
        "Alive & Well",
        "Alien Labs",
        "Astro Puff",
        "Astronauts",
        "Bear Labs",
        "Big Boy Dro",
        "BLEEZIE",
        "Blem",
        "BLOOM",
        "Boutiq",
        "Buddies Brand",
        "CABO",
        "Cannabiotix",
        "Cannavis",
        "CARTÉ",
        "Casual",
        "Chico Verde",
        "Claybourne Co.",
        "Clsics",
        "Coldfire Extracts",
        "Connected Cannabis Co.",
        "Cream of the Crop",
        "Creme De Canna",
        "CRU Cannabis",
        "Cure Injoy",
        "Dabwoods",
        "Decibel Gardens",
        "Dee Thai",
        "Delighted",
        "Dime Bag",
        "Dime Industries",
        "Dr. Norm's",
        "Enjoyable",
        "Feelz",
        "Fields Family Farmz",
        "Flav",
        "Flavorade",
        "Froot",
        "Frost",
        "FYPM",
        "Fuzed",
        "ghost.",
        "Ghostpack",
        "Go Loco",
        "Gramlin",
        "Greenline",
        "Happy Fruit",
        "Heavy Hitters",
        "Heirbloom Legacy Flower",
        "High 90s",
        "High Garden",
        "Highatus",
        "HOTBOX™",
        "iKrusher",
        "IMKING",
        "Jeeter",
        "Jetpacks",
        "Just J",
        "Kiva Confections",
        "KONEZ",
        "Korova",
        "Kushagram",
        "KushCompany",
        "Life Cannabis Co",
        "Littles",
        "Locals Only Concentrates",
        "Loopy Sanchez",
        "Lucky Thirteen",
        "Malibu Premium Cannabis",
        "Marygold",
        "Martians",
        "Maven Genetics",
        "Micro Bar",
        "Muha Meds",
        "Nameless Genetics",
        "Net Wt.",
        "Not Your Father's",
        "Oakfruitland",
        "Oishii",
        "Old Pal",
        "Originals",
        "Pabst (PBR)",
        "Papa's Herb",
        "Plugplay",
        "Popstar",
        "Pressure Extracts",
        "PUFF",
        "Punch Edibles & Extracts",
        "Pure Vape",
        "Quiet Kings",
        "Quickies Prerolls",
        "Raw Garden™",
        "Raw Sins",
        "Rockstar",
        "Rooted",
        "Rove",
        "Russian Roulette",
        "Saida",
        "SELFiES",
        "Sherbinskis",
        "Sluggers Hit",
        "Smokiez Edibles",
        "Solis",
        "Sparkiez",
        "ST Ides",
        "STIIIZY",
        "Sundae",
        "Tempo",
        "The Cure Company",
        "THC Design",
        "Traditional",
        "Turn",
        "Twisters",
        "Uncle Arnies",
        "Wave Rider Nursery",
        "West Coast Cure",
        "West Coast Trading Company",
        "West Coast Treez",
        "WVY",
        "WYLD",
        "Yada Yada",
        "Zero Gravity",
        "Zips",
    ]

    /// Merges the catalog list with brands dynamically found on ProductSKU records,
    /// deduplicates (case-insensitive), and returns a sorted list.
    static func merged(with dynamicBrands: [String]) -> [String] {
        var seen = Set<String>()
        var result: [String] = []
        for brand in (all + dynamicBrands.filter { !$0.isEmpty }) {
            let key = brand.lowercased()
            if seen.insert(key).inserted {
                result.append(brand)
            }
        }
        return result.sorted { $0.lowercased() < $1.lowercased() }
    }
}
